name: VyntriWitherStorm
main: com.vyntriloop.minecraft.witherstorm.VyntriWitherStormPlugin
version: 1.1.0
author: VyntriLoop
commands:
  witherstorm:
    description: Shows the Vyntri Wither Storm plugin status
    usage: /witherstorm status
